### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by znicholls**
Continuation of #46 (don't merge both)

- [ ] Tests added
- [ ] Documentation added
- [ ] Example added (in the documentation, to an existing notebook, or in a new notebook)
- [ ] Description in ``CHANGELOG.rst`` added (single line such as: ``(`#XX <https://github.com/iiasa/climate-assessment/pull/XX>`_) Added feature which does something``)

### CODE REVIEW

**Comment by znicholls** [comment]
@phackstock I got some of the way but then crashed into https://github.com/IAMconsortium/pyam/issues/793 which I think is the reason that the remaining tests are failing (because it causes a regression in the behaviour of `reclassify_waste_and_other_co2_ar6`)

**Comment by phackstock** [comment]
@jkikstra, if you could take this one that would be great. I'll need to update our Scenario Explorer processing container soon and that will require pandas 2.0 which currently breaks those tests.

**Comment by jkikstra** [comment]
Thanks for the initial work and figuring out the issue! 
Will try to tackle this at the end of this week.

**Comment by phackstock** [comment]
Perfect, thanks a lot @jkikstra!

**Comment by jkikstra** [comment]
Started working on it now, but stopping for today.

Starting a list here for changes that I think we need to be making:

- replace require_variable with require_data (in utils.py)
- check why pyam.concat is now failing in `reclassify_waste_and_other_co2_ar6()` (in checks.py), perhaps it is due to the changes for `exclude`? https://github.com/IAMconsortium/pyam/pull/759, meaning df.extracols is not the same for the two dataframes on line 843

**Comment by znicholls** [comment]
Closing in favour of #50

**Pull request closed without merging**
