### PR TITLE
Add CITATION.cff

### PR DESCRIPTION
**Pull request by phackstock**
Adding a `CITATION.cff` file so that it will be picked up by Zenodo for future releases.
For `v0.1.0` I'll manually add the authors.
The authors are taken from `setup.cfg`.

### CODE REVIEW

**Review by znicholls — COMMENTED** [review]
Should we also include the paper citation? I've never really worked out how to get the repo vs. paper citation thing work nicely. Maybe you have good examples from other stuff

**Comment by jkikstra** [comment]
Paper citation is included in docs already, and probably should be linked on the Zenodo as well indeed.

Otherwise lgtm.

**Comment by znicholls** [comment]
I think you can do multiple references somehow in the citation file?

**Comment by phackstock** [comment]
Ah true, I'll add some more info then.

**Comment by phackstock** [comment]
I added some more info about the license and the DOIs from zenodo (both the version specific and the overall one)
@jkikstra, does the paper have a DOI yet? If so we could add it as well. If not I'd merge this PR and then work towards release 0.1.1 after we've merged #6.

**Comment by jkikstra** [comment]
Thanks. No DOI yet.

**Pull request merged**
