### PR TITLE
Update documentation for citations and input file formats

### PR DESCRIPTION
**Pull request by jkikstra**
Updates documentation:

- First commit: be more explicit about input data (not .xls, only .xlsx or .csv)
- Second commit: update citations to Nicholls et al. (2022) and Kikstra et al. (2022), and fix Zenodo links where necessary

Adresses https://github.com/iiasa/climate-assessment/issues/25

### CODE REVIEW

**Comment by phackstock** [comment]
> Looks like a test is failing because of a numpy update;
I guess there's two ways of fixing this, pinning the numpy version or changing `np.float` to `float`. I would say the latter is preferred.

**Comment by jkikstra** [comment]
> > Looks like a test is failing because of a numpy update;
> 
> I guess there's two ways of fixing this, pinning the numpy version or changing `np.float` to `float`. I would say the latter is preferred.

Yes - just need to find where it is actually used, will try and go down the rabbit hole

**Comment by phackstock** [comment]
If you, for now, pin the version at `numpy <= 1.19` it should be fine (see the deprecation section of the numpy 1.20 release notes https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations). 
Once cicero addresses the numpy issue you can remove the version pin.

**Comment by jkikstra** [comment]
OK. 

Have made an issue on openscm-runner; https://github.com/openscm/openscm-runner/issues/81

**Comment by lewisjared** [comment]
Thanks for the MR @jkikstra. If the current master branch of openscm-runner fixes the tests, I'll make a new release.

**Comment by lewisjared** [comment]
Sorry I missed this. I just cut a new release so that should be available in the next hour

**Comment by lewisjared** [comment]
Hitting a few roadblocks regarding test coverage so it might not be resolved today, but I'll fix as soon as I can

**Comment by jkikstra** [comment]
Adjusted, and passing tests now.

**Pull request merged**
